/**
 * 自动生成，请勿手改。由 VS Code 的 Seti 图标主题导出。
 * 重新生成：pnpm --filter @piggy/desktop icons:seti
 *
 * 来源：extensions/theme-seti/icons/vs-seti-icon-theme.json
 * 许可：seti-ui，MIT，Copyright (c) 2014 Jesse Weed（见 THIRD_PARTY_NOTICES.md）
 */

/** 字形 + 颜色；键名与 Seti 的 iconDefinitions 一致。 */
export interface SetiDef {
  /** 字体码点（已是可直接渲染的字符） */
  c: string;
  /** 十六进制颜色；缺省时继承当前文字色 */
  f?: string;
}

export const SETI_DEFS: Record<string, SetiDef> = {
  "_R_light": { c: "", f: "#498ba7" },
  "_R": { c: "", f: "#519aba" },
  "_argdown_light": { c: "", f: "#498ba7" },
  "_argdown": { c: "", f: "#519aba" },
  "_asm_light": { c: "", f: "#b8383d" },
  "_asm": { c: "", f: "#cc3e44" },
  "_audio_light": { c: "", f: "#9068b0" },
  "_audio": { c: "", f: "#a074c4" },
  "_babel_light": { c: "", f: "#b7b73b" },
  "_babel": { c: "", f: "#cbcb41" },
  "_bazel_light": { c: "", f: "#7fae42" },
  "_bazel": { c: "", f: "#8dc149" },
  "_bazel_1_light": { c: "", f: "#455155" },
  "_bazel_1": { c: "", f: "#4d5a5e" },
  "_bicep_light": { c: "", f: "#498ba7" },
  "_bicep": { c: "", f: "#519aba" },
  "_bower_light": { c: "", f: "#cc6d2e" },
  "_bower": { c: "", f: "#e37933" },
  "_bsl_light": { c: "", f: "#b8383d" },
  "_bsl": { c: "", f: "#cc3e44" },
  "_c_light": { c: "", f: "#498ba7" },
  "_c": { c: "", f: "#519aba" },
  "_c-sharp_light": { c: "", f: "#498ba7" },
  "_c-sharp": { c: "", f: "#519aba" },
  "_c_1_light": { c: "", f: "#9068b0" },
  "_c_1": { c: "", f: "#a074c4" },
  "_c_2_light": { c: "", f: "#b7b73b" },
  "_c_2": { c: "", f: "#cbcb41" },
  "_cake_light": { c: "", f: "#b8383d" },
  "_cake": { c: "", f: "#cc3e44" },
  "_cake_php_light": { c: "", f: "#b8383d" },
  "_cake_php": { c: "", f: "#cc3e44" },
  "_clock_light": { c: "", f: "#498ba7" },
  "_clock": { c: "", f: "#519aba" },
  "_clock_1_light": { c: "", f: "#627379" },
  "_clock_1": { c: "", f: "#6d8086" },
  "_clojure_light": { c: "", f: "#7fae42" },
  "_clojure": { c: "", f: "#8dc149" },
  "_clojure_1_light": { c: "", f: "#498ba7" },
  "_clojure_1": { c: "", f: "#519aba" },
  "_code-climate_light": { c: "", f: "#7fae42" },
  "_code-climate": { c: "", f: "#8dc149" },
  "_code-search_light": { c: "", f: "#9068b0" },
  "_code-search": { c: "", f: "#a074c4" },
  "_coffee_light": { c: "", f: "#b7b73b" },
  "_coffee": { c: "", f: "#cbcb41" },
  "_coldfusion_light": { c: "", f: "#498ba7" },
  "_coldfusion": { c: "", f: "#519aba" },
  "_config_light": { c: "", f: "#627379" },
  "_config": { c: "", f: "#6d8086" },
  "_cpp_light": { c: "", f: "#498ba7" },
  "_cpp": { c: "", f: "#519aba" },
  "_cpp_1_light": { c: "", f: "#9068b0" },
  "_cpp_1": { c: "", f: "#a074c4" },
  "_cpp_2_light": { c: "", f: "#b7b73b" },
  "_cpp_2": { c: "", f: "#cbcb41" },
  "_crystal_light": { c: "", f: "#bfc2c1" },
  "_crystal": { c: "", f: "#d4d7d6" },
  "_crystal_embedded_light": { c: "", f: "#bfc2c1" },
  "_crystal_embedded": { c: "", f: "#d4d7d6" },
  "_css_light": { c: "", f: "#498ba7" },
  "_css": { c: "", f: "#519aba" },
  "_csv_light": { c: "", f: "#7fae42" },
  "_csv": { c: "", f: "#8dc149" },
  "_cu_light": { c: "", f: "#7fae42" },
  "_cu": { c: "", f: "#8dc149" },
  "_cu_1_light": { c: "", f: "#9068b0" },
  "_cu_1": { c: "", f: "#a074c4" },
  "_d_light": { c: "", f: "#b8383d" },
  "_d": { c: "", f: "#cc3e44" },
  "_dart_light": { c: "", f: "#498ba7" },
  "_dart": { c: "", f: "#519aba" },
  "_db_light": { c: "", f: "#dd4b78" },
  "_db": { c: "", f: "#f55385" },
  "_db_1_light": { c: "", f: "#498ba7" },
  "_db_1": { c: "", f: "#519aba" },
  "_default_light": { c: "", f: "#bfc2c1" },
  "_default": { c: "", f: "#d4d7d6" },
  "_docker_light": { c: "", f: "#498ba7" },
  "_docker": { c: "", f: "#519aba" },
  "_docker_1_light": { c: "", f: "#455155" },
  "_docker_1": { c: "", f: "#4d5a5e" },
  "_docker_2_light": { c: "", f: "#7fae42" },
  "_docker_2": { c: "", f: "#8dc149" },
  "_docker_3_light": { c: "", f: "#dd4b78" },
  "_docker_3": { c: "", f: "#f55385" },
  "_ejs_light": { c: "", f: "#b7b73b" },
  "_ejs": { c: "", f: "#cbcb41" },
  "_elixir_light": { c: "", f: "#9068b0" },
  "_elixir": { c: "", f: "#a074c4" },
  "_elixir_script_light": { c: "", f: "#9068b0" },
  "_elixir_script": { c: "", f: "#a074c4" },
  "_elm_light": { c: "", f: "#498ba7" },
  "_elm": { c: "", f: "#519aba" },
  "_eslint_light": { c: "", f: "#9068b0" },
  "_eslint": { c: "", f: "#a074c4" },
  "_eslint_1_light": { c: "", f: "#455155" },
  "_eslint_1": { c: "", f: "#4d5a5e" },
  "_ethereum_light": { c: "", f: "#498ba7" },
  "_ethereum": { c: "", f: "#519aba" },
  "_f-sharp_light": { c: "", f: "#498ba7" },
  "_f-sharp": { c: "", f: "#519aba" },
  "_favicon_light": { c: "", f: "#b7b73b" },
  "_favicon": { c: "", f: "#cbcb41" },
  "_firebase_light": { c: "", f: "#cc6d2e" },
  "_firebase": { c: "", f: "#e37933" },
  "_firefox_light": { c: "", f: "#cc6d2e" },
  "_firefox": { c: "", f: "#e37933" },
  "_font_light": { c: "", f: "#b8383d" },
  "_font": { c: "", f: "#cc3e44" },
  "_git_light": { c: "", f: "#3b4b52" },
  "_git": { c: "", f: "#41535b" },
  "_github_light": { c: "", f: "#bfc2c1" },
  "_github": { c: "", f: "#d4d7d6" },
  "_gitlab_light": { c: "", f: "#cc6d2e" },
  "_gitlab": { c: "", f: "#e37933" },
  "_go_light": { c: "", f: "#498ba7" },
  "_go": { c: "", f: "#519aba" },
  "_go2_light": { c: "", f: "#498ba7" },
  "_go2": { c: "", f: "#519aba" },
  "_godot_light": { c: "", f: "#498ba7" },
  "_godot": { c: "", f: "#519aba" },
  "_godot_1_light": { c: "", f: "#b8383d" },
  "_godot_1": { c: "", f: "#cc3e44" },
  "_godot_2_light": { c: "", f: "#b7b73b" },
  "_godot_2": { c: "", f: "#cbcb41" },
  "_godot_3_light": { c: "", f: "#9068b0" },
  "_godot_3": { c: "", f: "#a074c4" },
  "_gradle_light": { c: "", f: "#498ba7" },
  "_gradle": { c: "", f: "#519aba" },
  "_grails_light": { c: "", f: "#7fae42" },
  "_grails": { c: "", f: "#8dc149" },
  "_graphql_light": { c: "", f: "#dd4b78" },
  "_graphql": { c: "", f: "#f55385" },
  "_grunt_light": { c: "", f: "#cc6d2e" },
  "_grunt": { c: "", f: "#e37933" },
  "_gulp_light": { c: "", f: "#b8383d" },
  "_gulp": { c: "", f: "#cc3e44" },
  "_hacklang_light": { c: "", f: "#cc6d2e" },
  "_hacklang": { c: "", f: "#e37933" },
  "_haml_light": { c: "", f: "#b8383d" },
  "_haml": { c: "", f: "#cc3e44" },
  "_happenings_light": { c: "", f: "#498ba7" },
  "_happenings": { c: "", f: "#519aba" },
  "_haskell_light": { c: "", f: "#9068b0" },
  "_haskell": { c: "", f: "#a074c4" },
  "_haxe_light": { c: "", f: "#cc6d2e" },
  "_haxe": { c: "", f: "#e37933" },
  "_haxe_1_light": { c: "", f: "#b7b73b" },
  "_haxe_1": { c: "", f: "#cbcb41" },
  "_haxe_2_light": { c: "", f: "#498ba7" },
  "_haxe_2": { c: "", f: "#519aba" },
  "_haxe_3_light": { c: "", f: "#9068b0" },
  "_haxe_3": { c: "", f: "#a074c4" },
  "_heroku_light": { c: "", f: "#9068b0" },
  "_heroku": { c: "", f: "#a074c4" },
  "_hex_light": { c: "", f: "#b8383d" },
  "_hex": { c: "", f: "#cc3e44" },
  "_html_light": { c: "", f: "#498ba7" },
  "_html": { c: "", f: "#519aba" },
  "_html_1_light": { c: "", f: "#7fae42" },
  "_html_1": { c: "", f: "#8dc149" },
  "_html_2_light": { c: "", f: "#b7b73b" },
  "_html_2": { c: "", f: "#cbcb41" },
  "_html_3_light": { c: "", f: "#cc6d2e" },
  "_html_3": { c: "", f: "#e37933" },
  "_html_erb_light": { c: "", f: "#b8383d" },
  "_html_erb": { c: "", f: "#cc3e44" },
  "_ignored_light": { c: "", f: "#3b4b52" },
  "_ignored": { c: "", f: "#41535b" },
  "_illustrator_light": { c: "", f: "#b7b73b" },
  "_illustrator": { c: "", f: "#cbcb41" },
  "_image_light": { c: "", f: "#9068b0" },
  "_image": { c: "", f: "#a074c4" },
  "_info_light": { c: "", f: "#498ba7" },
  "_info": { c: "", f: "#519aba" },
  "_ionic_light": { c: "", f: "#498ba7" },
  "_ionic": { c: "", f: "#519aba" },
  "_jade_light": { c: "", f: "#b8383d" },
  "_jade": { c: "", f: "#cc3e44" },
  "_java_light": { c: "", f: "#b8383d" },
  "_java": { c: "", f: "#cc3e44" },
  "_java_1_light": { c: "", f: "#498ba7" },
  "_java_1": { c: "", f: "#519aba" },
  "_javascript_light": { c: "", f: "#b7b73b" },
  "_javascript": { c: "", f: "#cbcb41" },
  "_javascript_1_light": { c: "", f: "#cc6d2e" },
  "_javascript_1": { c: "", f: "#e37933" },
  "_javascript_2_light": { c: "", f: "#498ba7" },
  "_javascript_2": { c: "", f: "#519aba" },
  "_jenkins_light": { c: "", f: "#b8383d" },
  "_jenkins": { c: "", f: "#cc3e44" },
  "_jinja_light": { c: "", f: "#b8383d" },
  "_jinja": { c: "", f: "#cc3e44" },
  "_json_light": { c: "", f: "#b7b73b" },
  "_json": { c: "", f: "#cbcb41" },
  "_json_1_light": { c: "", f: "#7fae42" },
  "_json_1": { c: "", f: "#8dc149" },
  "_julia_light": { c: "", f: "#9068b0" },
  "_julia": { c: "", f: "#a074c4" },
  "_karma_light": { c: "", f: "#7fae42" },
  "_karma": { c: "", f: "#8dc149" },
  "_kotlin_light": { c: "", f: "#cc6d2e" },
  "_kotlin": { c: "", f: "#e37933" },
  "_less_light": { c: "", f: "#498ba7" },
  "_less": { c: "", f: "#519aba" },
  "_license_light": { c: "", f: "#b7b73b" },
  "_license": { c: "", f: "#cbcb41" },
  "_license_1_light": { c: "", f: "#cc6d2e" },
  "_license_1": { c: "", f: "#e37933" },
  "_license_2_light": { c: "", f: "#b8383d" },
  "_license_2": { c: "", f: "#cc3e44" },
  "_liquid_light": { c: "", f: "#7fae42" },
  "_liquid": { c: "", f: "#8dc149" },
  "_livescript_light": { c: "", f: "#498ba7" },
  "_livescript": { c: "", f: "#519aba" },
  "_lock_light": { c: "", f: "#7fae42" },
  "_lock": { c: "", f: "#8dc149" },
  "_lua_light": { c: "", f: "#498ba7" },
  "_lua": { c: "", f: "#519aba" },
  "_makefile_light": { c: "", f: "#cc6d2e" },
  "_makefile": { c: "", f: "#e37933" },
  "_makefile_1_light": { c: "", f: "#9068b0" },
  "_makefile_1": { c: "", f: "#a074c4" },
  "_makefile_2_light": { c: "", f: "#627379" },
  "_makefile_2": { c: "", f: "#6d8086" },
  "_makefile_3_light": { c: "", f: "#498ba7" },
  "_makefile_3": { c: "", f: "#519aba" },
  "_markdown_light": { c: "", f: "#498ba7" },
  "_markdown": { c: "", f: "#519aba" },
  "_maven_light": { c: "", f: "#b8383d" },
  "_maven": { c: "", f: "#cc3e44" },
  "_mdo_light": { c: "", f: "#b8383d" },
  "_mdo": { c: "", f: "#cc3e44" },
  "_mustache_light": { c: "", f: "#cc6d2e" },
  "_mustache": { c: "", f: "#e37933" },
  "_nim_light": { c: "", f: "#b7b73b" },
  "_nim": { c: "", f: "#cbcb41" },
  "_notebook_light": { c: "", f: "#498ba7" },
  "_notebook": { c: "", f: "#519aba" },
  "_npm_light": { c: "", f: "#3b4b52" },
  "_npm": { c: "", f: "#41535b" },
  "_npm_1_light": { c: "", f: "#b8383d" },
  "_npm_1": { c: "", f: "#cc3e44" },
  "_npm_ignored_light": { c: "", f: "#3b4b52" },
  "_npm_ignored": { c: "", f: "#41535b" },
  "_nunjucks_light": { c: "", f: "#7fae42" },
  "_nunjucks": { c: "", f: "#8dc149" },
  "_ocaml_light": { c: "", f: "#cc6d2e" },
  "_ocaml": { c: "", f: "#e37933" },
  "_odata_light": { c: "", f: "#cc6d2e" },
  "_odata": { c: "", f: "#e37933" },
  "_pddl_light": { c: "", f: "#9068b0" },
  "_pddl": { c: "", f: "#a074c4" },
  "_pdf_light": { c: "", f: "#b8383d" },
  "_pdf": { c: "", f: "#cc3e44" },
  "_perl_light": { c: "", f: "#498ba7" },
  "_perl": { c: "", f: "#519aba" },
  "_photoshop_light": { c: "", f: "#498ba7" },
  "_photoshop": { c: "", f: "#519aba" },
  "_php_light": { c: "", f: "#9068b0" },
  "_php": { c: "", f: "#a074c4" },
  "_pipeline_light": { c: "", f: "#cc6d2e" },
  "_pipeline": { c: "", f: "#e37933" },
  "_plan_light": { c: "", f: "#7fae42" },
  "_plan": { c: "", f: "#8dc149" },
  "_platformio_light": { c: "", f: "#cc6d2e" },
  "_platformio": { c: "", f: "#e37933" },
  "_powershell_light": { c: "", f: "#498ba7" },
  "_powershell": { c: "", f: "#519aba" },
  "_prisma_light": { c: "", f: "#498ba7" },
  "_prisma": { c: "", f: "#519aba" },
  "_prolog_light": { c: "", f: "#cc6d2e" },
  "_prolog": { c: "", f: "#e37933" },
  "_pug_light": { c: "", f: "#b8383d" },
  "_pug": { c: "", f: "#cc3e44" },
  "_puppet_light": { c: "", f: "#b7b73b" },
  "_puppet": { c: "", f: "#cbcb41" },
  "_purescript_light": { c: "", f: "#bfc2c1" },
  "_purescript": { c: "", f: "#d4d7d6" },
  "_python_light": { c: "", f: "#498ba7" },
  "_python": { c: "", f: "#519aba" },
  "_react_light": { c: "", f: "#498ba7" },
  "_react": { c: "", f: "#519aba" },
  "_react_1_light": { c: "", f: "#cc6d2e" },
  "_react_1": { c: "", f: "#e37933" },
  "_reasonml_light": { c: "", f: "#b8383d" },
  "_reasonml": { c: "", f: "#cc3e44" },
  "_rescript_light": { c: "", f: "#b8383d" },
  "_rescript": { c: "", f: "#cc3e44" },
  "_rescript_1_light": { c: "", f: "#dd4b78" },
  "_rescript_1": { c: "", f: "#f55385" },
  "_rollup_light": { c: "", f: "#b8383d" },
  "_rollup": { c: "", f: "#cc3e44" },
  "_ruby_light": { c: "", f: "#b8383d" },
  "_ruby": { c: "", f: "#cc3e44" },
  "_rust_light": { c: "", f: "#627379" },
  "_rust": { c: "", f: "#6d8086" },
  "_salesforce_light": { c: "", f: "#498ba7" },
  "_salesforce": { c: "", f: "#519aba" },
  "_sass_light": { c: "", f: "#dd4b78" },
  "_sass": { c: "", f: "#f55385" },
  "_sbt_light": { c: "", f: "#498ba7" },
  "_sbt": { c: "", f: "#519aba" },
  "_scala_light": { c: "", f: "#b8383d" },
  "_scala": { c: "", f: "#cc3e44" },
  "_shell_light": { c: "", f: "#7fae42" },
  "_shell": { c: "", f: "#8dc149" },
  "_slim_light": { c: "", f: "#cc6d2e" },
  "_slim": { c: "", f: "#e37933" },
  "_smarty_light": { c: "", f: "#b7b73b" },
  "_smarty": { c: "", f: "#cbcb41" },
  "_spring_light": { c: "", f: "#7fae42" },
  "_spring": { c: "", f: "#8dc149" },
  "_stylelint_light": { c: "", f: "#bfc2c1" },
  "_stylelint": { c: "", f: "#d4d7d6" },
  "_stylelint_1_light": { c: "", f: "#455155" },
  "_stylelint_1": { c: "", f: "#4d5a5e" },
  "_stylus_light": { c: "", f: "#7fae42" },
  "_stylus": { c: "", f: "#8dc149" },
  "_sublime_light": { c: "", f: "#cc6d2e" },
  "_sublime": { c: "", f: "#e37933" },
  "_svelte_light": { c: "", f: "#b8383d" },
  "_svelte": { c: "", f: "#cc3e44" },
  "_svg_light": { c: "", f: "#9068b0" },
  "_svg": { c: "", f: "#a074c4" },
  "_svg_1_light": { c: "", f: "#498ba7" },
  "_svg_1": { c: "", f: "#519aba" },
  "_swift_light": { c: "", f: "#cc6d2e" },
  "_swift": { c: "", f: "#e37933" },
  "_terraform_light": { c: "", f: "#9068b0" },
  "_terraform": { c: "", f: "#a074c4" },
  "_tex_light": { c: "", f: "#498ba7" },
  "_tex": { c: "", f: "#519aba" },
  "_tex_1_light": { c: "", f: "#b7b73b" },
  "_tex_1": { c: "", f: "#cbcb41" },
  "_tex_2_light": { c: "", f: "#cc6d2e" },
  "_tex_2": { c: "", f: "#e37933" },
  "_tex_3_light": { c: "", f: "#bfc2c1" },
  "_tex_3": { c: "", f: "#d4d7d6" },
  "_todo": { c: "" },
  "_tsconfig_light": { c: "", f: "#498ba7" },
  "_tsconfig": { c: "", f: "#519aba" },
  "_twig_light": { c: "", f: "#7fae42" },
  "_twig": { c: "", f: "#8dc149" },
  "_typescript_light": { c: "", f: "#498ba7" },
  "_typescript": { c: "", f: "#519aba" },
  "_typescript_1_light": { c: "", f: "#cc6d2e" },
  "_typescript_1": { c: "", f: "#e37933" },
  "_vala_light": { c: "", f: "#627379" },
  "_vala": { c: "", f: "#6d8086" },
  "_video_light": { c: "", f: "#dd4b78" },
  "_video": { c: "", f: "#f55385" },
  "_vite_light": { c: "", f: "#b7b73b" },
  "_vite": { c: "", f: "#cbcb41" },
  "_vue_light": { c: "", f: "#7fae42" },
  "_vue": { c: "", f: "#8dc149" },
  "_wasm_light": { c: "", f: "#9068b0" },
  "_wasm": { c: "", f: "#a074c4" },
  "_wat_light": { c: "", f: "#9068b0" },
  "_wat": { c: "", f: "#a074c4" },
  "_webpack_light": { c: "", f: "#498ba7" },
  "_webpack": { c: "", f: "#519aba" },
  "_wgt_light": { c: "", f: "#498ba7" },
  "_wgt": { c: "", f: "#519aba" },
  "_windows_light": { c: "", f: "#498ba7" },
  "_windows": { c: "", f: "#519aba" },
  "_word_light": { c: "", f: "#498ba7" },
  "_word": { c: "", f: "#519aba" },
  "_xls_light": { c: "", f: "#7fae42" },
  "_xls": { c: "", f: "#8dc149" },
  "_xml_light": { c: "", f: "#cc6d2e" },
  "_xml": { c: "", f: "#e37933" },
  "_yarn_light": { c: "", f: "#498ba7" },
  "_yarn": { c: "", f: "#519aba" },
  "_yml_light": { c: "", f: "#9068b0" },
  "_yml": { c: "", f: "#a074c4" },
  "_zig_light": { c: "", f: "#cc6d2e" },
  "_zig": { c: "", f: "#e37933" },
  "_zip_light": { c: "", f: "#b8383d" },
  "_zip": { c: "", f: "#cc3e44" },
  "_zip_1_light": { c: "", f: "#627379" },
  "_zip_1": { c: "", f: "#6d8086" },
};

/** 扩展名（小写，不含点）→ 图标键 */
export const SETI_EXT: Record<string, string> = {
  "bsl": "_bsl",
  "mdo": "_mdo",
  "cls": "_salesforce",
  "apex": "_salesforce",
  "asm": "_asm",
  "s": "_asm",
  "bicep": "_bicep",
  "bzl": "_bazel",
  "bazel": "_bazel",
  "build": "_bazel",
  "workspace": "_bazel",
  "bazelignore": "_bazel",
  "bazelversion": "_bazel",
  "h": "_c_1",
  "aspx": "_html",
  "ascx": "_html_1",
  "asax": "_html_2",
  "master": "_html_2",
  "hh": "_cpp_1",
  "hpp": "_cpp_1",
  "hxx": "_cpp_1",
  "h++": "_cpp_1",
  "edn": "_clojure_1",
  "cfc": "_coldfusion",
  "cfm": "_coldfusion",
  "litcoffee": "_coffee",
  "config": "_config",
  "cr": "_crystal",
  "ecr": "_crystal_embedded",
  "slang": "_crystal_embedded",
  "cson": "_json",
  "css.map": "_css",
  "sss": "_css",
  "csv": "_csv",
  "xls": "_xls",
  "xlsx": "_xls",
  "cuh": "_cu_1",
  "hu": "_cu_1",
  "cake": "_cake",
  "ctp": "_cake_php",
  "d": "_d",
  "doc": "_word",
  "docx": "_word",
  "ejs": "_ejs",
  "ex": "_elixir",
  "exs": "_elixir_script",
  "elm": "_elm",
  "ico": "_favicon",
  "gitconfig": "_git",
  "gitkeep": "_git",
  "gitattributes": "_git",
  "gitmodules": "_git",
  "slide": "_go",
  "article": "_go",
  "gd": "_godot",
  "godot": "_godot_1",
  "tres": "_godot_2",
  "tscn": "_godot_3",
  "gradle": "_gradle",
  "gsp": "_grails",
  "gql": "_graphql",
  "graphql": "_graphql",
  "graphqls": "_graphql",
  "hack": "_hacklang",
  "haml": "_haml",
  "hs": "_haskell",
  "lhs": "_haskell",
  "hx": "_haxe",
  "hxs": "_haxe_1",
  "hxp": "_haxe_2",
  "hxml": "_haxe_3",
  "jade": "_jade",
  "class": "_java_1",
  "classpath": "_java",
  "js.map": "_javascript",
  "cjs.map": "_javascript",
  "mjs.map": "_javascript",
  "spec.js": "_javascript_1",
  "spec.cjs": "_javascript_1",
  "spec.mjs": "_javascript_1",
  "test.js": "_javascript_1",
  "test.cjs": "_javascript_1",
  "test.mjs": "_javascript_1",
  "es": "_javascript",
  "es5": "_javascript",
  "es7": "_javascript",
  "jinja": "_jinja",
  "jinja2": "_jinja",
  "kt": "_kotlin",
  "kts": "_kotlin",
  "liquid": "_liquid",
  "ls": "_livescript",
  "argdown": "_argdown",
  "ad": "_argdown",
  "mustache": "_mustache",
  "stache": "_mustache",
  "nim": "_nim",
  "nims": "_nim",
  "github-issues": "_github",
  "ipynb": "_notebook",
  "njk": "_nunjucks",
  "nunjucks": "_nunjucks",
  "nunjs": "_nunjucks",
  "nunj": "_nunjucks",
  "njs": "_nunjucks",
  "nj": "_nunjucks",
  "npm-debug.log": "_npm",
  "npmignore": "_npm_1",
  "npmrc": "_npm_1",
  "ml": "_ocaml",
  "mli": "_ocaml",
  "cmx": "_ocaml",
  "cmxa": "_ocaml",
  "odata": "_odata",
  "php.inc": "_php",
  "pipeline": "_pipeline",
  "pddl": "_pddl",
  "plan": "_plan",
  "happenings": "_happenings",
  "prisma": "_prisma",
  "pp": "_puppet",
  "epp": "_puppet",
  "purs": "_purescript",
  "spec.jsx": "_react_1",
  "test.jsx": "_react_1",
  "cjsx": "_react",
  "spec.tsx": "_react_1",
  "test.tsx": "_react_1",
  "re": "_reasonml",
  "res": "_rescript",
  "resi": "_rescript_1",
  "r": "_R",
  "rmd": "_R",
  "erb": "_html_erb",
  "erb.html": "_html_erb",
  "html.erb": "_html_erb",
  "sass": "_sass",
  "springbeans": "_spring",
  "slim": "_slim",
  "smarty.tpl": "_smarty",
  "tpl": "_smarty",
  "sbt": "_sbt",
  "scala": "_scala",
  "sol": "_ethereum",
  "styl": "_stylus",
  "svelte": "_svelte",
  "soql": "_db_1",
  "tf": "_terraform",
  "tf.json": "_terraform",
  "tfvars": "_terraform",
  "tfvars.json": "_terraform",
  "dtx": "_tex_2",
  "ins": "_tex_3",
  "toml": "_config",
  "twig": "_twig",
  "spec.ts": "_typescript_1",
  "test.ts": "_typescript_1",
  "vala": "_vala",
  "vapi": "_vala",
  "component": "_html_3",
  "vue": "_vue",
  "wasm": "_wasm",
  "wat": "_wat",
  "pro": "_prolog",
  "zig": "_zig",
  "jar": "_zip",
  "zip": "_zip_1",
  "wgt": "_wgt",
  "ai": "_illustrator",
  "psd": "_photoshop",
  "pdf": "_pdf",
  "eot": "_font",
  "ttf": "_font",
  "woff": "_font",
  "woff2": "_font",
  "otf": "_font",
  "avif": "_image",
  "gif": "_image",
  "jpg": "_image",
  "jpeg": "_image",
  "png": "_image",
  "pxm": "_image",
  "svg": "_svg",
  "svgx": "_image",
  "tiff": "_image",
  "webp": "_image",
  "sublime-project": "_sublime",
  "sublime-workspace": "_sublime",
  "mov": "_video",
  "ogv": "_video",
  "webm": "_video",
  "avi": "_video",
  "mpg": "_video",
  "mp4": "_video",
  "mp3": "_audio",
  "ogg": "_audio",
  "wav": "_audio",
  "flac": "_audio",
  "3ds": "_svg_1",
  "3dm": "_svg_1",
  "stl": "_svg_1",
  "obj": "_svg_1",
  "dae": "_svg_1",
  "babelrc": "_babel",
  "babelrc.js": "_babel",
  "babelrc.cjs": "_babel",
  "bazelrc": "_bazel_1",
  "bowerrc": "_bower",
  "dockerignore": "_docker_1",
  "codeclimate.yml": "_code-climate",
  "eslintrc": "_eslint",
  "eslintrc.js": "_eslint",
  "eslintrc.cjs": "_eslint",
  "eslintrc.yaml": "_eslint",
  "eslintrc.yml": "_eslint",
  "eslintrc.json": "_eslint",
  "eslintignore": "_eslint_1",
  "firebaserc": "_firebase",
  "gitlab-ci.yml": "_gitlab",
  "jshintrc": "_javascript_2",
  "jscsrc": "_javascript_2",
  "stylelintrc": "_stylelint",
  "stylelintrc.json": "_stylelint",
  "stylelintrc.yaml": "_stylelint",
  "stylelintrc.yml": "_stylelint",
  "stylelintrc.js": "_stylelint",
  "stylelintignore": "_stylelint_1",
  "direnv": "_config",
  "static": "_config",
  "slugignore": "_config",
  "tmp": "_clock_1",
  "htaccess": "_config",
  "key": "_lock",
  "cert": "_lock",
  "cer": "_lock",
  "crt": "_lock",
  "pem": "_lock",
  "ds_store": "_ignored",
};

/** 完整文件名（小写）→ 图标键 */
export const SETI_NAME: Record<string, string> = {
  "mix": "_hex",
  "karma.conf.js": "_karma",
  "karma.conf.cjs": "_karma",
  "karma.conf.mjs": "_karma",
  "karma.conf.coffee": "_karma",
  "readme.md": "_info",
  "readme.txt": "_info",
  "readme": "_info",
  "changelog.md": "_clock",
  "changelog.txt": "_clock",
  "changelog": "_clock",
  "changes.md": "_clock",
  "changes.txt": "_clock",
  "changes": "_clock",
  "version.md": "_clock",
  "version.txt": "_clock",
  "version": "_clock",
  "mvnw": "_maven",
  "pom.xml": "_maven",
  "tsconfig.json": "_tsconfig",
  "vite.config.js": "_vite",
  "vite.config.ts": "_vite",
  "vite.config.mjs": "_vite",
  "vite.config.mts": "_vite",
  "vite.config.cjs": "_vite",
  "vite.config.cts": "_vite",
  "swagger.json": "_json_1",
  "swagger.yml": "_json_1",
  "swagger.yaml": "_json_1",
  "mime.types": "_config",
  "jenkinsfile": "_jenkins",
  "babel.config.js": "_babel",
  "babel.config.json": "_babel",
  "babel.config.cjs": "_babel",
  "build": "_bazel",
  "build.bazel": "_bazel",
  "workspace": "_bazel",
  "workspace.bazel": "_bazel",
  "bower.json": "_bower",
  "docker-healthcheck": "_docker_2",
  "eslint.config.js": "_eslint",
  "firebase.json": "_firebase",
  "geckodriver": "_firefox",
  "gruntfile.js": "_grunt",
  "gruntfile.babel.js": "_grunt",
  "gruntfile.coffee": "_grunt",
  "gulpfile": "_gulp",
  "gulpfile.js": "_gulp",
  "ionic.config.json": "_ionic",
  "ionic.project": "_ionic",
  "platformio.ini": "_platformio",
  "rollup.config.js": "_rollup",
  "sass-lint.yml": "_sass",
  "stylelint.config.js": "_stylelint",
  "stylelint.config.cjs": "_stylelint",
  "stylelint.config.mjs": "_stylelint",
  "yarn.clean": "_yarn",
  "yarn.lock": "_yarn",
  "webpack.config.js": "_webpack",
  "webpack.config.cjs": "_webpack",
  "webpack.config.mjs": "_webpack",
  "webpack.config.ts": "_webpack",
  "webpack.config.build.js": "_webpack",
  "webpack.config.build.cjs": "_webpack",
  "webpack.config.build.mjs": "_webpack",
  "webpack.config.build.ts": "_webpack",
  "webpack.common.js": "_webpack",
  "webpack.common.cjs": "_webpack",
  "webpack.common.mjs": "_webpack",
  "webpack.common.ts": "_webpack",
  "webpack.dev.js": "_webpack",
  "webpack.dev.cjs": "_webpack",
  "webpack.dev.mjs": "_webpack",
  "webpack.dev.ts": "_webpack",
  "webpack.prod.js": "_webpack",
  "webpack.prod.cjs": "_webpack",
  "webpack.prod.mjs": "_webpack",
  "webpack.prod.ts": "_webpack",
  "license": "_license",
  "licence": "_license",
  "license.txt": "_license",
  "licence.txt": "_license",
  "license.md": "_license",
  "licence.md": "_license",
  "copying": "_license",
  "copying.txt": "_license",
  "copying.md": "_license",
  "compiling": "_license_1",
  "compiling.txt": "_license_1",
  "compiling.md": "_license_1",
  "contributing": "_license_2",
  "contributing.txt": "_license_2",
  "contributing.md": "_license_2",
  "qmakefile": "_makefile_1",
  "omakefile": "_makefile_2",
  "cmakelists.txt": "_makefile_3",
  "procfile": "_heroku",
  "todo": "_todo",
  "todo.txt": "_todo",
  "todo.md": "_todo",
  "npm-debug.log": "_npm_ignored",
};

/** 语言 id → 图标键（Monaco/文件树按语言回退时用） */
export const SETI_LANG: Record<string, string> = {
  "bat": "_windows",
  "clojure": "_clojure",
  "coffeescript": "_coffee",
  "jsonc": "_json",
  "json": "_json",
  "c": "_c",
  "cpp": "_cpp",
  "cuda-cpp": "_cu",
  "csharp": "_c-sharp",
  "css": "_css",
  "dart": "_dart",
  "dockerfile": "_docker",
  "dotenv": "_config",
  "ignore": "_git",
  "fsharp": "_f-sharp",
  "git-commit": "_git",
  "go": "_go2",
  "groovy": "_grails",
  "handlebars": "_mustache",
  "html": "_html_3",
  "properties": "_config",
  "java": "_java",
  "javascriptreact": "_react",
  "javascript": "_javascript",
  "julia": "_julia",
  "tex": "_tex_1",
  "latex": "_tex",
  "less": "_less",
  "lua": "_lua",
  "makefile": "_makefile",
  "markdown": "_markdown",
  "objective-c": "_c_2",
  "objective-cpp": "_cpp_2",
  "perl": "_perl",
  "php": "_php",
  "powershell": "_powershell",
  "jade": "_pug",
  "python": "_python",
  "r": "_R",
  "razor": "_html",
  "ruby": "_ruby",
  "rust": "_rust",
  "scss": "_sass",
  "search-result": "_code-search",
  "shellscript": "_shell",
  "sql": "_db",
  "swift": "_swift",
  "typescript": "_typescript",
  "typescriptreact": "_react",
  "xml": "_xml",
  "dockercompose": "_docker_3",
  "yaml": "_yml",
  "argdown": "_argdown",
  "bicep": "_bicep",
  "elixir": "_elixir",
  "elm": "_elm",
  "erb": "_html_erb",
  "github-issues": "_github",
  "gradle": "_gradle",
  "godot": "_godot",
  "haml": "_haml",
  "haskell": "_haskell",
  "haxe": "_haxe",
  "jinja": "_jinja",
  "kotlin": "_kotlin",
  "mustache": "_mustache",
  "nunjucks": "_nunjucks",
  "ocaml": "_ocaml",
  "rescript": "_rescript",
  "sass": "_sass",
  "stylus": "_stylus",
  "terraform": "_terraform",
  "todo": "_todo",
  "vala": "_vala",
  "vue": "_vue",
  "jsonl": "_json",
  "postcss": "_css",
  "django-html": "_html_3",
  "blade": "_php",
  "prompt": "_markdown",
  "instructions": "_markdown",
  "chatagent": "_markdown",
  "skill": "_markdown",
};

/** 默认文件图标键 */
export const SETI_FILE = "_default";
