// @generated by apps/desktop/scripts/gen-plugin-builtins.mjs —— 请勿手改，改脚本后重跑。
//
// 数据来源：pi v0.87.1（git 898ab8040）
//   packages/coding-agent/src/extensions/index.ts   builtInExtensions
//
// pi 的内置扩展没有运行时枚举接口（RPC 无扩展命令、`pi list` 只列 settings 的包），
// 所以只能在编译期固化。**随 pi 版本漂移**：升级 pi 后重跑本脚本（--check 可用于 CI）。
//
// 重新生成：node apps/desktop/scripts/gen-plugin-builtins.mjs <pi 源码根>

/// pi 的内置扩展（inline factory）。
///
/// `hidden` = pi 自己在启动横幅里也不显示它（`interactive-mode.ts:1741`）；
/// 对用户而言它**既不能卸载也不能停用**——`--no-extensions` 也拦不住 inline factory
/// （`resource-loader.ts:559-567`）。界面必须如实标注。
pub struct Builtin {
    pub name: &'static str,
    pub hidden: bool,
    pub path: &'static str,
}

/// pi 0.87.1 的 1 个内置扩展。
pub const BUILTINS: &[Builtin] = &[
    Builtin { name: "llama.cpp", hidden: true, path: "(pi 内置：packages/coding-agent/src/extensions/llama)" },
];
