// @generated by apps/desktop/scripts/gen-provider-catalog.mjs —— 请勿手改，改脚本后重跑。
//
// 数据来源：pi v0.87.1（git 898ab8040）
//   packages/ai/src/types.ts            KnownProvider 联合（合法 id 全集）
//   packages/ai/src/providers/all.ts    builtinProviders()（顺序 + id↔实现文件）
//   packages/ai/src/providers/*.ts      createProvider({ id, name, baseUrl, api })
//   packages/ai/src/env-api-keys.ts     envMap / 特例分支（该 provider 读哪个环境变量）
//
// 字段含义与"空值代表什么"见 catalog.rs；这里只陈述 pi 源码里写了什么，
// 不替 pi 做任何推断（没写 baseUrl 就是空串，不猜）。
//
// 重新生成：node apps/desktop/scripts/gen-provider-catalog.mjs <pi 源码根>

use super::CatalogEntry as C;

/// pi 0.87.1 的提供商目录，41 条，顺序 = `builtinProviders()` 的顺序。
pub const CATALOG: &[C] = &[
    C { id: "amazon-bedrock", name: "Amazon Bedrock", base_url: "", api: "bedrock-converse-stream", env_var: "", apis: &["bedrock-converse-stream"] },
    C { id: "ant-ling", name: "Ant Ling", base_url: "https://api.ant-ling.com/v1", api: "openai-completions", env_var: "ANT_LING_API_KEY", apis: &["openai-completions"] },
    C { id: "anthropic", name: "Anthropic", base_url: "https://api.anthropic.com", api: "anthropic-messages", env_var: "ANTHROPIC_API_KEY", apis: &["anthropic-messages"] },
    C { id: "azure-openai-responses", name: "Azure OpenAI", base_url: "", api: "azure-openai-responses", env_var: "AZURE_OPENAI_API_KEY", apis: &["azure-openai-responses"] },
    C { id: "baseten", name: "Baseten", base_url: "https://inference.baseten.co/v1", api: "openai-completions", env_var: "BASETEN_API_KEY", apis: &["openai-completions"] },
    C { id: "cerebras", name: "Cerebras", base_url: "https://api.cerebras.ai/v1", api: "openai-completions", env_var: "CEREBRAS_API_KEY", apis: &["openai-completions"] },
    C { id: "cloudflare-ai-gateway", name: "Cloudflare AI Gateway", base_url: "", api: "openai-completions", env_var: "CLOUDFLARE_API_KEY", apis: &["anthropic-messages", "openai-completions", "openai-responses"] },
    C { id: "cloudflare-workers-ai", name: "Cloudflare Workers AI", base_url: "", api: "openai-completions", env_var: "CLOUDFLARE_API_KEY", apis: &["openai-completions"] },
    C { id: "deepseek", name: "DeepSeek", base_url: "https://api.deepseek.com", api: "openai-completions", env_var: "DEEPSEEK_API_KEY", apis: &["openai-completions"] },
    C { id: "fireworks", name: "Fireworks", base_url: "https://api.fireworks.ai/inference", api: "openai-completions", env_var: "FIREWORKS_API_KEY", apis: &["anthropic-messages", "openai-completions"] },
    C { id: "github-copilot", name: "GitHub Copilot", base_url: "https://api.individual.githubcopilot.com", api: "openai-completions", env_var: "COPILOT_GITHUB_TOKEN", apis: &["anthropic-messages", "openai-completions", "openai-responses"] },
    C { id: "google", name: "Google", base_url: "https://generativelanguage.googleapis.com/v1beta", api: "google-generative-ai", env_var: "GEMINI_API_KEY", apis: &["google-generative-ai"] },
    C { id: "google-vertex", name: "Google Vertex AI", base_url: "", api: "google-vertex", env_var: "GOOGLE_CLOUD_API_KEY", apis: &["google-vertex"] },
    C { id: "groq", name: "Groq", base_url: "https://api.groq.com/openai/v1", api: "openai-completions", env_var: "GROQ_API_KEY", apis: &["openai-completions"] },
    C { id: "huggingface", name: "Hugging Face", base_url: "https://router.huggingface.co/v1", api: "openai-completions", env_var: "HF_TOKEN", apis: &["openai-completions"] },
    C { id: "kimi-coding", name: "Kimi For Coding", base_url: "https://api.kimi.com/coding", api: "anthropic-messages", env_var: "KIMI_API_KEY", apis: &["anthropic-messages"] },
    C { id: "meta", name: "Meta", base_url: "https://api.meta.ai/v1", api: "openai-responses", env_var: "META_API_KEY", apis: &["openai-responses"] },
    C { id: "minimax", name: "MiniMax", base_url: "https://api.minimax.io/anthropic", api: "anthropic-messages", env_var: "MINIMAX_API_KEY", apis: &["anthropic-messages"] },
    C { id: "minimax-cn", name: "MiniMax CN", base_url: "https://api.minimaxi.com/anthropic", api: "anthropic-messages", env_var: "MINIMAX_CN_API_KEY", apis: &["anthropic-messages"] },
    C { id: "mistral", name: "Mistral", base_url: "https://api.mistral.ai", api: "mistral-conversations", env_var: "MISTRAL_API_KEY", apis: &["mistral-conversations"] },
    C { id: "moonshotai", name: "Moonshot AI", base_url: "https://api.moonshot.ai/v1", api: "openai-completions", env_var: "MOONSHOT_API_KEY", apis: &["openai-completions"] },
    C { id: "moonshotai-cn", name: "Moonshot AI CN", base_url: "https://api.moonshot.cn/v1", api: "openai-completions", env_var: "MOONSHOT_API_KEY", apis: &["openai-completions"] },
    C { id: "nvidia", name: "NVIDIA", base_url: "https://integrate.api.nvidia.com/v1", api: "openai-completions", env_var: "NVIDIA_API_KEY", apis: &["openai-completions"] },
    C { id: "openai", name: "OpenAI", base_url: "https://api.openai.com/v1", api: "openai-responses", env_var: "OPENAI_API_KEY", apis: &["openai-responses"] },
    C { id: "openai-codex", name: "OpenAI Codex", base_url: "https://chatgpt.com/backend-api", api: "openai-codex-responses", env_var: "", apis: &["openai-codex-responses"] },
    C { id: "opencode", name: "OpenCode Zen", base_url: "", api: "openai-completions", env_var: "OPENCODE_API_KEY", apis: &["anthropic-messages", "google-generative-ai", "openai-completions", "openai-responses"] },
    C { id: "opencode-go", name: "OpenCode Go", base_url: "", api: "openai-completions", env_var: "OPENCODE_API_KEY", apis: &["anthropic-messages", "openai-completions", "openai-responses"] },
    C { id: "openrouter", name: "OpenRouter", base_url: "https://openrouter.ai/api/v1", api: "openai-completions", env_var: "OPENROUTER_API_KEY", apis: &["anthropic-messages", "openai-completions"] },
    C { id: "qwen-token-plan", name: "Qwen Token Plan", base_url: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1", api: "openai-completions", env_var: "QWEN_TOKEN_PLAN_API_KEY", apis: &["openai-completions"] },
    C { id: "qwen-token-plan-cn", name: "Qwen Token Plan CN", base_url: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1", api: "openai-completions", env_var: "QWEN_TOKEN_PLAN_CN_API_KEY", apis: &["openai-completions"] },
    C { id: "qwen-token-plan-individual", name: "Qwen Token Plan Individual", base_url: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1", api: "openai-completions", env_var: "QWEN_TOKEN_PLAN_API_KEY", apis: &["openai-completions"] },
    C { id: "radius", name: "Radius", base_url: "", api: "pi-messages", env_var: "RADIUS_API_KEY", apis: &[] },
    C { id: "together", name: "Together", base_url: "https://api.together.ai/v1", api: "openai-completions", env_var: "TOGETHER_API_KEY", apis: &["openai-completions"] },
    C { id: "vercel-ai-gateway", name: "Vercel AI Gateway", base_url: "https://ai-gateway.vercel.sh", api: "anthropic-messages", env_var: "AI_GATEWAY_API_KEY", apis: &["anthropic-messages"] },
    C { id: "xai", name: "xAI", base_url: "https://api.x.ai/v1", api: "openai-responses", env_var: "XAI_API_KEY", apis: &["openai-responses"] },
    C { id: "xiaomi", name: "Xiaomi", base_url: "https://api.xiaomimimo.com/v1", api: "openai-completions", env_var: "XIAOMI_API_KEY", apis: &["openai-completions"] },
    C { id: "xiaomi-token-plan-ams", name: "Xiaomi Token Plan AMS", base_url: "https://token-plan-ams.xiaomimimo.com/v1", api: "openai-completions", env_var: "XIAOMI_TOKEN_PLAN_AMS_API_KEY", apis: &["openai-completions"] },
    C { id: "xiaomi-token-plan-cn", name: "Xiaomi Token Plan CN", base_url: "https://token-plan-cn.xiaomimimo.com/v1", api: "openai-completions", env_var: "XIAOMI_TOKEN_PLAN_CN_API_KEY", apis: &["openai-completions"] },
    C { id: "xiaomi-token-plan-sgp", name: "Xiaomi Token Plan SGP", base_url: "https://token-plan-sgp.xiaomimimo.com/v1", api: "openai-completions", env_var: "XIAOMI_TOKEN_PLAN_SGP_API_KEY", apis: &["openai-completions"] },
    C { id: "zai", name: "Z.AI", base_url: "https://api.z.ai/api/coding/paas/v4", api: "openai-completions", env_var: "ZAI_API_KEY", apis: &["openai-completions"] },
    C { id: "zai-coding-cn", name: "Z.AI Coding CN", base_url: "https://open.bigmodel.cn/api/coding/paas/v4", api: "openai-completions", env_var: "ZAI_CODING_CN_API_KEY", apis: &["openai-completions"] },
];

/// pi 认识的 API 协议（`types.ts` 的 `KnownApi`），10 条。
/// pi 的 `Api` 类型是 `KnownApi | (string & {})` —— 自定义协议字符串也合法，
/// 所以这只是"界面默认给哪些选项"，不是白名单。
pub const KNOWN_APIS: &[&str] = &["openai-completions", "mistral-conversations", "openai-responses", "azure-openai-responses", "openai-codex-responses", "anthropic-messages", "bedrock-converse-stream", "google-generative-ai", "google-vertex", "pi-messages"];
